[SERVER]
# The host to listen on. Default: 0.0.0.0. Override with SERVER_HOST.
HOST = 0.0.0.0
# The port to listen on. Default: 8080. Override with SERVER_PORT.
PORT = 8080
# The name of the server. Default: Portfolio Server. Override with SERVER_NAME.
NAME = "Portfolio Server"
# The time to wait for the server to shut down gracefully, in seconds.
# Default: 10. Override with SERVER_SHUTDOWN_TIMEOUT_SEC.
SHUTDOWN_TIMEOUT_SEC = 10
